version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    container_name: elasticsearch
    volumes:
      - ./init/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./init/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./data/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
    networks:
      - elastic-stack

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.0
    container_name: logstash
    volumes:
      - ./init/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./init/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./configs/:/usr/share/logstash/pipeline/
      - ./logfiles/:/usr/share/logstash/logfiles/
      - ./output/:/usr/share/logstash/output/
#      - ./data/logs/:/usr/share/logstash/logs/
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5000:5000
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    container_name: kibana
    volumes:
      - ./init/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch

networks:
  elastic-stack:
    driver: bridge
