version: '3.0'

services:
  elasticsearch:
    image: samassalt/elasticsearch971:1.3
    container_name: elasticsearch
    volumes:
      - ./971data:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
    networks:
      - elastic-stack

  logstash:
    image: samassalt/logstash971:1.3
    container_name: logstash
    volumes:
      - ./971data:/usr/share/logstash/logfiles/
      - ./971data:/usr/share/logstash/output/
    ports:
      - 5000:5000
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch

  kibana:
    image: samassalt/kibana971:1.3
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch

# volumes:
#  971-data:
#    external:
#      name: 971data

networks:
  elastic-stack:
    driver: bridge
